version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: annuaire
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
